version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: luna-memoir
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  luna_memoir_api:
    build: .
    depends_on:
      - db
    restart: always
    hostname: luna_memoir_api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: luna-memoir
      HOST: 0.0.0.0

    ports:
      - 6001:6001

  luna_memoir_frontend:
    build:
      context: ../luna-memoir-frontend
      dockerfile: Dockerfile
    volumes:
      - ../luna-memoir-frontend/dist/luna-memoir-frontend/browser:/usr/share/nginx/html/
    ports:
      - 6002:80

  luna_memoir_adminer:
    image: adminer
    restart: always
    container_name: luna_memoir_adminer
    hostname: luna_memoir_adminer
    ports:
      - 6003:8080

volumes:
  pgdata:
    external: false
