export enum DreamCategoryEnum {
  OTHER = 'OTHER',
  LUCID = 'LUCID',
  NIGHTMARE = 'NIGHTMARE',
  DAYDREAM = 'DAYDREAM',
  RECURRING = 'RECURRING',
  FANTASY = 'FANTASY',
  PROPHETIC = 'PROPHETIC',
  VIVID = 'VIVID',
  HEALING = 'HEALING',
}
